### ISSUE TITLE
Inverted Encoder

### ISSUE THREAD

**Issue by benblakehart** [nullbitsco/tidbit#3]
I attempted to load the default keymap and the encoder in position 1, top row, appears to be inverted (i.e. clockwise decreases volume, cc increases).

**Comment by jaygreco** [comment]
The encoders are flipped between the two shared channels (the top left and top right options, both labeled 1 in the build guide). The encoder direction is also flipped between releases 1.1 and beyond, so you can flash an earlier (or later) build depending on which one you started with and it will be resolved.

Otherwise, this is easily remedied by swapping the below lines in `config.h` and recompiling:
``` c
#define ENCODERS_PAD_A { B2 }
#define ENCODERS_PAD_B { B3 }
```
