### ISSUE TITLE
OLED Keymap Error

### ISSUE THREAD

**Issue by hyphonetics** [nullbitsco/tidbit#6]
When attempting to compile the firmware for the OLED map QMK MSYS gives me the following error and I'm not sure how to go about fixing it <br>
`Compiling: keyboards/tidbit/keymaps/oled/keymap.c
      keyboards/tidbit/keymaps/oled/keymap.c:132:6: error: conflicting types for 'encoder_update_user'
 void encoder_update_user(uint8_t index, bool clockwise) {
      ^~~~~~~~~~~~~~~~~~~
In file included from quantum/quantum.h:204,
                 from keyboards/tidbit/tidbit.h:3,
                 from keyboards/tidbit/keymaps/oled/keymap.c:17:
quantum/encoder.h:26:6: note: previous declaration of 'encoder_update_user' was here
 bool encoder_update_user(uint8_t index, bool clockwise);`

**Comment by jaygreco** [comment]
This is a recent issue that has come up due to QMK changing the return type of the encoder function. I haven't had time to make the changes in this repo yet. There's some discussion in the discord server about this issue and how to resolve it, if you're on discord and want to pop in: https://discord.com/channels/735314509949829151/735317782626959479/859891938421112832
(The messages before and after give more context/info)

**Comment by hyphonetics** [comment]
After some poking around I seem to have gotten it to compile without issue, I changed lines 132-138 from 
>void encoder_update_user(uint8_t index, bool clockwise) {
  if (clockwise) {
    tap_code(KC_VOLU);
  } else {
    tap_code(KC_VOLD);
  }  
}

to 

>bool encoder_update_user(uint8_t index, bool clockwise) {
  if (clockwise) {
    tap_code(KC_VOLU);
  } else {
    tap_code(KC_VOLD);
  }
  return true;
}

I have yet to test it yet, still in the process of building the pcb, but the firmware compiled without an error

**Comment by jaygreco** [comment]
Closed by #9 👍
